### ISSUE TITLE
CUDA Hardware requirements

### ISSUE THREAD

**Issue by claymodel** [sony/nnabla-ext-cuda#243]
Appreciate if you kindly list up the  cuda requirements

**Comment by TE-andrewshin** [comment]
Note that nnabla only supports CUDA 9.2 or later.
If you'd like to know the compute capability by GPU models, please refer to Table 2 in this document https://docs.nvidia.com/pdf/CUDA_Compatibility.pdf

**Comment by TakuyaNarihira** [comment]
Closing since no update for a while.
