### ISSUE TITLE
When is the next release planned?

### ISSUE THREAD

**Issue by Shin-Ogata** [sony/nnabla-ext-cuda#470]
Thank you for your hard work.

If possible, we would like to know when you are planning the next release of `nnabla-ext-cuda`.
We need a fixed version for a [problem with GCC 11](https://github.com/sony/nnabla-ext-cuda/issues/467).

If it is scheduled to be released soon, we would like to wait for it.
Regards,

**Comment by TomonobuTsujikawa** [comment]
Sorry for taking time.
I can't give you a specific date for next release.
But many bug fixes have been merged into master branch, so there is much possibility that it will be released in the near future (in June?)

**Comment by TomonobuTsujikawa** [comment]
Sorry, it's already over June (mid of July...), but the latest wheel is available on PyPI now.
https://pypi.org/project/nnabla/#history

The release blog is available here:
https://blog.nnabla.org/release/v1-36-0/

**Comment by Shin-Ogata** [comment]
I forgot to contact you. sorry.
We have confirmed that this issue has been fixed in this environment as well.
Thanks a lot.

**Comment by TomonobuTsujikawa** [comment]
Thank you for confirmation!
So, please let me close this issue.
